#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/src/Services/Reader/UploadFileCommand.php';

use FileReader\UploadFileCommand;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new UploadFileCommand());
$app->run();